---
docker_packages:
  - docker-ce
  - docker-ce-cli
  - containerd.io


debian_prereqs:
  - apt-transport-https
  - ca-certificates
  - curl
  - gnupg
  - lsb-release

redhat_prereqs:
  - yum-utils
  - device-mapper-persistent-data
  - lvm2