---
- name: Install NTP package
  package:
    name: "{{ ntp_package }}"
    state: present

- name: Deploy NTP config
  template:
    src: "{{ ntp_package }}.conf.j2"
    dest: "{{ ntp_config }}"
    owner: root
    group: root
    mode: '0644'
  tags: set_ntp_config

- name: Set timezone
  timezone:
    name: "{{ ntp_timezone }}"
  tags: set_timezone

- name: Enable and start NTP service
  service:
    name: "{{ ntp_service }}"
    state: started
    enabled: yes

- name: Check NTP status
  command: "{{ 'chronyc sources' if ntp_service == 'chronyd' else 'ntpq -p' }}"
  register: ntp_status
  changed_when: false
  failed_when: ntp_status.rc != 0
  tags: check_ntp

- name: Print NTP status
  debug:
    var: ntp_status.stdout_lines
  tags: print_ntp
