---
- name: Configure the firewall
  firewalld:
    service: "{{ item }}"
    state: enabled
    permanent: true
    immediate: true
    zone: public
  loop:
    - nfs
    - ssh
  when: ansible_os_family == "RedHat"
  tags: configure_firewall



- name: Configure the  firewall
  ufw:
    rule: allow
    name: "{{ item }}"
  loop:
    - nfs
    - ssh
  when: ansible_os_family == "Debian"
  tags: configure_firewall


- name: Install NFS packages
  package:
    name: "{{ nfs_packages[ansible_facts['os_family']] }}"
    state: present
  notify: start_nfs_server
  tags: install_nfs_packages
