---
- name: Configure the firewall
  firewalld:
    service: "{{ item }}"
    state: enabled
    permanent: true
    immediate: true
    zone: public
  loop:
    - nfs
    - ssh
  when: ansible_os_family == "RedHat"
  tags: configure_firewall



- name: Configure the  firewall
  ufw:
    rule: allow
    name: "{{ item }}"
  loop:
    - nfs
    - ssh
  when: ansible_os_family == "Debian"
  tags: configure_firewall


- name: Install NFS packages
  package:
    name: "{{ nfs_packages[ansible_facts['os_family']] }}"
    state: present
  tags: install_nfs_packages


- name: Start nfs server
  service:
    name: "{{ nfs_server_service[ansible_facts['os_family']] }}"
    state: started
    enabled: true
  tags: start_nfs_server


- name : Create directory for NFS 
  file:
    path: /nfs_dir
    state: directory
    mode: '0755'
    owner: nfsnobody
    group: nfsnobody
  tags: create_nfs_exports
